services:
  django:
    image: bccontractsregistry.azurecr.io/contracts-backend:latest
    command: sh -c "python3 manage.py migrate && python3 -m daphne -b 0.0.0.0 app.asgi:application --port 8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      WEB3_RPC: ${WEB3_RPC}
      CHAIN_ID: ${CHAIN_ID}
      IPFS_API: ${IPFS_API}
      AKEYLESS_STORE_NAME: ${AKEYLESS_STORE_NAME}
    ports:
      - "8000:8000"
  ganache:
    image: bccontractsregistry.azurecr.io/contracts-ganache:latest
    command:
      - --host=0.0.0.0
      - --port=8545
      - --chain.chainId=${GANACHE_CHAIN_ID}
      - --chain.networkId=${GANACHE_NETWORK_ID}
      - --wallet.mnemonic=${GANACHE_MNEMONIC}
      - --miner.defaultGasPrice=${GANACHE_GAS_PRICE}
    environment:
      GANACHE_PORT: "8545"
      GANACHE_CHAIN_ID: ${GANACHE_CHAIN_ID}
      GANACHE_NETWORK_ID: ${GANACHE_NETWORK_ID}
      GANACHE_MNEMONIC: ${GANACHE_MNEMONIC}
      GANACHE_GAS_PRICE: ${GANACHE_GAS_PRICE}
    ports:
      - "8545:8545"
  ipfs:
    image: bccontractsregistry.azurecr.io/contracts-ipfs:latest
    environment:
      IPFS_API: ${IPFS_API}
    ports:
      - "5001:5001"
      - "8080:8080"
      - "4001:4001"
  redis:
    image: redis:8.0-M04-bookworm
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
  frontend:
    image: bccontractsregistry.azurecr.io/contracts-frontend:latest
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    ports:
      - "3000:80"
