# Generated by Django 5.2.3 on 2025-07-05 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wallet_account_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(default='Student', max_length=100),
        ),
    ]
