# Generated by Django 5.2.3 on 2025-07-17 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_accountrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma_id', models.CharField(help_text='The keccak256 hash of the certificate PDF.', max_length=66, unique=True)),
                ('student_address', models.CharField(help_text='The Ethereum address of the student.', max_length=42)),
                ('issuer_address', models.CharField(help_text='The Ethereum address of the issuer.', max_length=42)),
                ('tx_hash', models.CharField(help_text='The transaction hash of the registration.', max_length=66, unique=True)),
                ('ipfs_hash', models.CharField(blank=True, help_text='The IPFS hash of the certificate PDF.', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
        migrations.RemoveField(
            model_name='accountrole',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_verifier',
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='mnemonic',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='private_key',
            field=models.CharField(max_length=66),
        ),
        migrations.AlterField(
            model_name='accountrole',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_address',
            field=models.CharField(max_length=42),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tx_hash',
            field=models.CharField(max_length=66, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
